name: Aerobotix
description: A robot who do navigation and mapping to make ads more interesting.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  fl_animated_linechart: ^1.1.6
  swipe_deck: ^1.1.0
  carousel_slider: ^4.1.1
  firebase_auth: ^3.4.2
  google_sign_in: ^5.4.0
  firebase_database: ^9.0.20
  pinput: ^2.2.11
  easy_container: ^1.0.4
  intl_phone_field: ^3.1.0
  firebase_phone_auth_handler:
  flutter_launcher_icons: ^0.9.3
  flutter_toggle_tab: ^1.2.0
  multi_select_flutter: ^4.1.2
  animated_button: ^0.2.0
  flutter_native_splash: ^2.2.7
  flutter_datetime_picker: ^1.5.1
  gender_picker: ^1.1.0
  firebase_storage: ^10.3.5
  image_picker: ^0.8.5+3
  path: ^1.8.1
  platform_device_id: ^1.0.1
  internet_connection_checker: ^0.0.1+4
  mobile_number: ^1.0.4
  url_launcher: ^6.1.5
  flutter_sms: ^2.3.3
  awesome_dialog: ^2.2.1
  confetti: ^0.7.0
  status_view: ^0.0.2
  avatar_glow: ^2.0.2
  flutter_vector_icons: ^1.0.0
  flutter_advanced_avatar: ^1.1.0
  editable_image: ^1.1.0
  glassmorphism: ^3.0.0
 
  audioplayers: ^1.0.1
  buttons_tabbar: ^1.3.6
  http: ^0.13.5
  youtube_api: ^1.0.4
 
 


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/profiles/
    - assets/images/badges/
    - assets/HomeScreen/
    - assets/audio/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png





